version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
  back-end:
    build: ./back-end
    ports:
      - "3001:3001"
    volumes:
      - logs:/app/logs
      - ./back-end:/app
      - /app/node_modules
    depends_on:
      - mongodb
  front-end:
    build: ./front-end
    ports:
      - "4000:4000"
    volumes:
      - ./front-end/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - back-end

volumes:
  data:
  logs:
